#!/usr/bin/env python3
"""
make_docs_index.py — regenerate docs/INDEX.md from the *_v[N].md design corpus.

Closes Phase 2.17 AC8. The project now has 60+ versioned design docs across
root + subfolders; this builds a navigable index grouped by domain, with each
entry's first heading line as the one-line purpose + last-modified date.

Idempotent: re-running just overwrites docs/INDEX.md with the current state.
Heartbeats and Cowork-Paul liaison turns should run this whenever a new _vN.md
lands; safe to run unconditionally.
"""
import re
import time
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "INDEX.md"

# Domain classification: list of (regex, domain_label). First match wins.
# Order matters — put more-specific patterns before generic ones.
DOMAINS = [
    (r"^c7_|^c8_|playtest", "Playtest / balance sim (C7–C8)"),
    (r"engine_determinism|pipeline_spec", "Engineering audits + specs"),
    (r"audio_", "Audio"),
    (r"cards_|archetypes|card_balance|gameplay_keywords|keywords_",
     "Card content + balance"),
    (r"bosses_|events_|curses_|shrines_|rests_|tokens_|warlord_tiers",
     "Run content (bosses / events / curses / shrines / tokens)"),
    (r"art_specs|art_pipeline|art_direction|faction_frames|sigils",
     "Art pipeline + specs"),
    (r"cosmetic_|theme_packs_|monetisation|shop_economy|battle_pass",
     "Monetisation + cosmetics"),
    (r"pvp_|extended_game_modes|competitive_landscape|collection_ui|"
     r"warlord_select|branching_map", "PvP / extended modes / UI screens"),
    (r"faction_lore|lore_gallowfell|^lore_|faction_bible", "Lore"),
    (r"gdd|GDD|internal_mvp_scope|phase1_brief|backlog",
     "Product scope + handover"),
]


def classify(name: str) -> str:
    for pattern, domain in DOMAINS:
        if re.search(pattern, name, re.IGNORECASE):
            return domain
    return "Uncategorised"


def first_heading_and_blurb(path: Path) -> tuple[str, str]:
    """Return (title, first_descriptive_line). Heuristic: skip the # H1 and
    take the next non-blank, non-status-tag line; otherwise the H1."""
    title = ""
    blurb = ""
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            s = line.strip()
            if not s:
                continue
            if s.startswith("#") and not title:
                title = s.lstrip("#").strip()
                continue
            if not blurb:
                # Drop the leading "**Status:** ..." line — find a real blurb.
                if s.startswith("**Status:**") or s.startswith("_Status:"):
                    continue
                blurb = s
                if len(blurb) > 180:
                    blurb = blurb[:177].rstrip() + "..."
                break
    except Exception as e:
        return ("(read error)", str(e))
    return (title or path.stem, blurb)


def collect_docs():
    by_domain = defaultdict(list)
    # Recursive scan, filtered.
    for p in sorted(ROOT.rglob("*.md")):
        rel = p.relative_to(ROOT).as_posix()
        if rel.startswith((".git/", "art_iterations/", "pipeline_setup/",
                           "node_modules/", "docs/INDEX")):
            continue
        # Versioned doc OR known-canonical top-level designs
        is_versioned = bool(re.search(r"_v\d+", p.stem, re.IGNORECASE))
        is_canon = p.stem in {
            "HANDOVER", "README", "HOW_TO_TEST", "IMAGE-GEN-SHOTLIST",
            "ART_INTEGRATION", "SHOWCASE_RUN", "backlog", "research_notes",
            "faction_bible", "lore_gallowfell", "art_direction",
            "monetisation_map", "internal_mvp_scope", "phase1_brief",
        }
        if not (is_versioned or is_canon):
            continue
        title, blurb = first_heading_and_blurb(p)
        mtime = time.strftime("%Y-%m-%d", time.localtime(p.stat().st_mtime))
        by_domain[classify(p.stem)].append((rel, title, blurb, mtime))
    return by_domain


def emit(by_domain):
    lines = [
        "# Design doc index",
        "",
        "_Auto-generated by `scripts/make_docs_index.py`. Do not hand-edit — "
        "re-run the script when a new `*_v[N].md` lands. Groups versioned "
        "design docs by domain so Paul / Cowork / Controller / Claude Code can "
        "navigate the 60+ doc corpus without grep. Last regenerated: "
        f"**{time.strftime('%Y-%m-%d')}**._",
        "",
    ]
    # Stable order: most-impactful domains first.
    order = [
        "Product scope + handover",
        "Card content + balance",
        "Run content (bosses / events / curses / shrines / tokens)",
        "Engineering audits + specs",
        "Playtest / balance sim (C7–C8)",
        "PvP / extended modes / UI screens",
        "Art pipeline + specs",
        "Audio",
        "Monetisation + cosmetics",
        "Lore",
        "Uncategorised",
    ]
    for domain in order:
        if domain not in by_domain:
            continue
        lines.append(f"## {domain}")
        lines.append("")
        for rel, title, blurb, mtime in sorted(by_domain[domain]):
            lines.append(f"- **[`{rel}`]({rel})** — {title}")
            if blurb:
                lines.append(f"  - _{mtime}_ — {blurb}")
            else:
                lines.append(f"  - _{mtime}_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    by_domain = collect_docs()
    total = sum(len(v) for v in by_domain.values())
    OUT.write_text(emit(by_domain), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {total} docs across "
          f"{len(by_domain)} domains")
    for d, items in sorted(by_domain.items(),
                            key=lambda kv: -len(kv[1])):
        print(f"  {d}: {len(items)}")


if __name__ == "__main__":
    main()
